# Generated by Django 5.0.2 on 2024-02-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('test_type', models.CharField(max_length=40)),
                ('image', models.ImageField(height_field=64, upload_to='img/', width_field=64)),
            ],
        ),
    ]
